require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '14.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorLocalNotifications', :path => '../../node_modules/@capacitor/local-notifications'
end

target 'App' do
  capacitor_pods

  # ✅ Firebase SDK 전체 추가
  pod 'FirebaseCore'
  pod 'FirebaseAnalytics'   # 이벤트 추적용
  pod 'FirebaseMessaging'   # 푸시 알림용
end

post_install do |installer|
  assertDeploymentTarget(installer)
end
